"""FastAPI application factory for NEXUS."""

from collections.abc import Callable
from datetime import datetime
from typing import Annotated
from uuid import UUID

from fastapi import Depends, FastAPI, HTTPException, Query, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from fastapi.security import APIKeyHeader, HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.orm import Session, sessionmaker

from nexus.api.schemas import (
    ErrorDetail,
    ErrorResponse,
    AgentCreateRequest,
    AgentView,
    ApprovalDecisionRequest,
    ApprovalDecisionView,
    ApprovalView,
    AuditEventView,
    ChangePasswordRequest,
    CredentialCreateRequest,
    CredentialCreatedResponse,
    CredentialView,
    LoginRequest,
    LoginResponse,
    OperationResponse,
    OperationResult,
    SessionView,
    UserView,
)
from nexus.database.models import (
    AgentCredential,
    AuditActorType,
    AuditEvent,
    OperationRequestRecord,
    User,
    UserSession,
)
from nexus.domain.authorization import (
    DecisionOutcome,
    DecisionReason,
    OperationRequest,
)
from nexus.database.session import get_session_factory
from nexus.repositories.agents import AgentRepository
from nexus.repositories.approvals import ApprovalRepository
from nexus.repositories.audit import AuditAction, AuditRepository
from nexus.repositories.identity import AgentCredentialRepository, UserSessionRepository
from nexus.repositories.operations import OperationRepository
from nexus.security.rbac import Capability, has_capability
from nexus.services.authorization import (
    IdempotencyConflictError,
    PersistentAuthorizationService,
    UnknownAgentError,
)
from nexus.services.identity import HumanAuthenticationService, InvalidCredentialsError
from nexus.services.approvals import (
    ApprovalConflictError,
    ApprovalNotFoundError,
    ApprovalService,
    OperationNotApprovableError,
)

agent_token_header = APIKeyHeader(
    name="X-Nexus-Agent-Token",
    scheme_name="AgentApiKey",
    description="Rotatable agent API key generated by the NEXUS server.",
    auto_error=False,
)
human_bearer = HTTPBearer(
    scheme_name="HumanSession",
    description="Opaque session token issued by /api/v1/auth/login",
    auto_error=False,
)


def create_app(
    session_factory: sessionmaker[Session] | None = None,
) -> FastAPI:
    """Create an application with optional test persistence adapters."""

    app = FastAPI(
        title="NEXUS Authorization API",
        version="0.5.0",
        description=(
            "Development API for simulated authorization decisions. It does not "
            "execute payments or other real financial operations."
        ),
    )
    app.state.session_factory = session_factory

    def database_factory() -> sessionmaker[Session]:
        return app.state.session_factory or get_session_factory()

    def require_agent_token(
        token: Annotated[str | None, Depends(agent_token_header)],
    ) -> str:
        if token is None:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail={
                    "code": "missing_agent_token",
                    "message": "X-Nexus-Agent-Token header is required",
                },
            )
        return token

    def authenticated_human(
        credentials: Annotated[
            HTTPAuthorizationCredentials | None, Depends(human_bearer)
        ],
    ) -> UserSession:
        if credentials is None or credentials.scheme.lower() != "bearer":
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail={"code": "invalid_session", "message": "valid session required"},
            )
        with database_factory()() as session:
            record = UserSessionRepository(session).authenticate(
                credentials.credentials
            )
            if record is None:
                raise HTTPException(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    detail={
                        "code": "invalid_session",
                        "message": "valid session required",
                    },
                )
            session.expunge(record.user)
            session.expunge(record)
            return record

    def require(capability: Capability) -> Callable[..., UserSession]:
        def dependency(
            human_session: Annotated[UserSession, Depends(authenticated_human)],
        ) -> UserSession:
            if not has_capability(human_session.user.role, capability):
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail={"code": "forbidden", "message": "permission denied"},
                )
            return human_session

        return dependency

    @app.exception_handler(HTTPException)
    async def http_error_handler(_request: Request, exc: HTTPException) -> JSONResponse:
        detail = exc.detail if isinstance(exc.detail, dict) else {}
        error = ErrorResponse(
            error=ErrorDetail(
                code=str(detail.get("code", "http_error")),
                message=str(detail.get("message", exc.detail)),
            )
        )
        return JSONResponse(status_code=exc.status_code, content=error.model_dump())

    @app.exception_handler(RequestValidationError)
    async def validation_error_handler(
        _request: Request, exc: RequestValidationError
    ) -> JSONResponse:
        error = ErrorResponse(
            error=ErrorDetail(
                code="request_validation_error",
                message="request body is invalid",
                details=list(exc.errors()),
            )
        )
        return JSONResponse(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            content=error.model_dump(mode="json"),
        )

    @app.post(
        "/api/v1/operations",
        response_model=OperationResponse,
        summary="Evaluate a simulated agent operation",
        description=(
            "Evaluates an operation against the authenticated agent's server-owned "
            "policy. No payment or real-world action is executed."
        ),
        responses={
            401: {"model": ErrorResponse, "description": "Missing or invalid token"},
            409: {"model": ErrorResponse, "description": "Idempotency conflict"},
            422: {"model": ErrorResponse, "description": "Invalid request body"},
        },
        tags=["Authorization"],
    )
    def submit_operation(
        operation: OperationRequest,
        token: Annotated[str, Depends(require_agent_token)],
    ) -> OperationResponse:
        with database_factory()() as session:
            service = PersistentAuthorizationService(session)
            try:
                decision = service.evaluate(token=token, request=operation)
            except UnknownAgentError as error:
                raise HTTPException(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    detail={
                        "code": "invalid_agent_token",
                        "message": "agent token is invalid",
                    },
                ) from error
            except IdempotencyConflictError as error:
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail={
                        "code": "idempotency_conflict",
                        "message": (
                            "request_id was already used by this agent with "
                            "different content"
                        ),
                    },
                ) from error
        return OperationResponse(
            data=OperationResult(
                request_id=decision.request_id,
                agent_id=decision.agent_id,
                operation=decision.operation,
                amount_cents=decision.amount_cents,
                outcome=decision.outcome,
                reason=decision.reason,
            )
        )

    def user_view(user: User) -> UserView:
        return UserView(
            id=user.id,
            company_id=user.company_id,
            name=user.name,
            email=user.email,
            role=user.role.value,
        )

    def credential_view(credential: AgentCredential) -> CredentialView:
        return CredentialView(
            id=credential.id,
            token_prefix=credential.token_prefix,
            created_at=credential.created_at,
            expires_at=credential.expires_at,
            revoked_at=credential.revoked_at,
            last_used_at=credential.last_used_at,
        )

    def approval_view(operation: OperationRequestRecord) -> ApprovalView:
        approval = operation.approval_decision
        return ApprovalView(
            operation_id=operation.id,
            request_id=operation.request_id,
            agent_id=operation.agent_id,
            agent_name=operation.agent.name,
            operation=operation.operation,
            amount_cents=operation.amount_cents,
            policy_outcome=DecisionOutcome(operation.outcome),
            policy_reason=DecisionReason(operation.reason),
            policy_snapshot=operation.policy_snapshot,
            created_at=operation.created_at,
            approval=(
                ApprovalDecisionView(
                    id=approval.id,
                    decision=approval.decision,
                    reason=approval.reason,
                    decided_by_user_id=approval.decided_by_user_id,
                    created_at=approval.created_at,
                )
                if approval is not None
                else None
            ),
        )

    def audit_view(event: AuditEvent) -> AuditEventView:
        return AuditEventView(
            id=event.id,
            actor_type=event.actor_type,
            actor_user_id=event.actor_user_id,
            actor_agent_id=event.actor_agent_id,
            action=event.action,
            target_type=event.target_type,
            target_id=event.target_id,
            metadata=event.metadata_json,
            created_at=event.created_at,
        )

    @app.post(
        "/api/v1/auth/login", response_model=LoginResponse, tags=["Human identity"]
    )
    def login(payload: LoginRequest) -> LoginResponse:
        with database_factory()() as session:
            try:
                record, token, user = HumanAuthenticationService(session).login(
                    company_slug=payload.company_slug,
                    email=str(payload.email),
                    password=payload.password,
                )
            except InvalidCredentialsError as error:
                raise HTTPException(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    detail={
                        "code": "invalid_credentials",
                        "message": "company, email, or password is invalid",
                    },
                ) from error
            return LoginResponse(
                token=token,
                session=SessionView(id=record.id, expires_at=record.expires_at),
                user=user_view(user),
            )

    @app.get("/api/v1/auth/me", response_model=UserView, tags=["Human identity"])
    def me(record: Annotated[UserSession, Depends(authenticated_human)]) -> UserView:
        return user_view(record.user)

    @app.post("/api/v1/auth/logout", status_code=204, tags=["Human identity"])
    def logout(
        record: Annotated[UserSession, Depends(authenticated_human)],
    ) -> None:
        with database_factory()() as session:
            stored = session.get(UserSession, record.id)
            if stored is not None:
                UserSessionRepository(session).revoke(stored)
                AuditRepository(session).add(
                    company_id=record.company_id,
                    actor_type=AuditActorType.HUMAN,
                    actor_user_id=record.user_id,
                    action=AuditAction.HUMAN_LOGOUT,
                    target_type="user_session",
                    target_id=record.id,
                )
                session.commit()

    @app.post("/api/v1/auth/change-password", status_code=204, tags=["Human identity"])
    def change_password(
        payload: ChangePasswordRequest,
        record: Annotated[UserSession, Depends(authenticated_human)],
    ) -> None:
        with database_factory()() as session:
            user = session.get(User, record.user_id)
            if user is None:
                raise HTTPException(
                    status_code=401,
                    detail={
                        "code": "invalid_session",
                        "message": "valid session required",
                    },
                )
            try:
                HumanAuthenticationService(session).change_password(
                    user,
                    current_password=payload.current_password,
                    new_password=payload.new_password,
                )
            except (InvalidCredentialsError, ValueError) as error:
                raise HTTPException(
                    status_code=400,
                    detail={"code": "password_change_failed", "message": str(error)},
                ) from error

    @app.get("/api/v1/agents", response_model=list[AgentView], tags=["Administration"])
    def list_agents(
        record: Annotated[UserSession, Depends(require(Capability.VIEW_AGENTS))],
    ) -> list[AgentView]:
        with database_factory()() as session:
            agents = AgentRepository(session).list_for_company(record.company_id)
            return [
                AgentView(
                    id=agent.id,
                    name=agent.name,
                    description=agent.description,
                    active=agent.active,
                    allowed_operations=sorted(p.operation for p in agent.permissions),
                    automatic_limit_cents=agent.automatic_limit_cents,
                    maximum_limit_cents=agent.maximum_limit_cents,
                )
                for agent in agents
            ]

    @app.post("/api/v1/agents", response_model=AgentView, tags=["Administration"])
    def create_agent(
        payload: AgentCreateRequest,
        record: Annotated[UserSession, Depends(require(Capability.CREATE_AGENTS))],
    ) -> AgentView:
        if payload.automatic_limit_cents > payload.maximum_limit_cents:
            raise HTTPException(
                status_code=422,
                detail={
                    "code": "invalid_limits",
                    "message": "automatic limit cannot exceed maximum limit",
                },
            )
        with database_factory()() as session:
            agent = AgentRepository(session).create(
                company_id=record.company_id,
                name=payload.name,
                description=payload.description,
                token=None,
                allowed_operations=payload.allowed_operations,
                automatic_limit_cents=payload.automatic_limit_cents,
                maximum_limit_cents=payload.maximum_limit_cents,
            )
            AuditRepository(session).add(
                company_id=record.company_id,
                actor_type=AuditActorType.HUMAN,
                actor_user_id=record.user_id,
                action=AuditAction.AGENT_CREATED,
                target_type="agent",
                target_id=agent.id,
                metadata={"name": agent.name},
            )
            session.commit()
            return AgentView(
                id=agent.id,
                name=agent.name,
                description=agent.description,
                active=agent.active,
                allowed_operations=sorted(p.operation for p in agent.permissions),
                automatic_limit_cents=agent.automatic_limit_cents,
                maximum_limit_cents=agent.maximum_limit_cents,
            )

    @app.post(
        "/api/v1/agents/{agent_id}/credentials",
        response_model=CredentialCreatedResponse,
        tags=["Administration"],
    )
    def create_credential(
        agent_id: UUID,
        payload: CredentialCreateRequest,
        record: Annotated[
            UserSession, Depends(require(Capability.MANAGE_AGENT_CREDENTIALS))
        ],
    ) -> CredentialCreatedResponse:
        with database_factory()() as session:
            agent = AgentRepository(session).get(
                company_id=record.company_id, agent_id=agent_id
            )
            if agent is None:
                raise HTTPException(
                    status_code=404,
                    detail={"code": "not_found", "message": "agent not found"},
                )
            credential, token = AgentCredentialRepository(session).create(
                agent, expires_at=payload.expires_at
            )
            AuditRepository(session).add(
                company_id=record.company_id,
                actor_type=AuditActorType.HUMAN,
                actor_user_id=record.user_id,
                action=AuditAction.CREDENTIAL_CREATED,
                target_type="agent_credential",
                target_id=credential.id,
                metadata={
                    "agent_id": str(agent.id),
                    "expires": bool(payload.expires_at),
                },
            )
            session.commit()
            return CredentialCreatedResponse(
                credential=credential_view(credential), token=token
            )

    @app.get(
        "/api/v1/agents/{agent_id}/credentials",
        response_model=list[CredentialView],
        tags=["Administration"],
    )
    def list_credentials(
        agent_id: UUID,
        record: Annotated[
            UserSession, Depends(require(Capability.MANAGE_AGENT_CREDENTIALS))
        ],
    ) -> list[CredentialView]:
        with database_factory()() as session:
            credentials = AgentCredentialRepository(session).list_for_agent(
                company_id=record.company_id, agent_id=agent_id
            )
            return [credential_view(item) for item in credentials]

    @app.post(
        "/api/v1/agents/{agent_id}/credentials/{credential_id}/revoke",
        status_code=204,
        tags=["Administration"],
    )
    def revoke_credential(
        agent_id: UUID,
        credential_id: UUID,
        record: Annotated[
            UserSession, Depends(require(Capability.MANAGE_AGENT_CREDENTIALS))
        ],
    ) -> None:
        with database_factory()() as session:
            repository = AgentCredentialRepository(session)
            credential = repository.get(
                company_id=record.company_id,
                agent_id=agent_id,
                credential_id=credential_id,
            )
            if credential is None:
                raise HTTPException(
                    status_code=404,
                    detail={"code": "not_found", "message": "credential not found"},
                )
            repository.revoke(credential)
            AuditRepository(session).add(
                company_id=record.company_id,
                actor_type=AuditActorType.HUMAN,
                actor_user_id=record.user_id,
                action=AuditAction.CREDENTIAL_REVOKED,
                target_type="agent_credential",
                target_id=credential.id,
                metadata={"agent_id": str(agent_id)},
            )
            session.commit()

    @app.get(
        "/api/v1/operations",
        response_model=list[OperationResult],
        tags=["Administration"],
    )
    def list_operations(
        record: Annotated[UserSession, Depends(require(Capability.VIEW_OPERATIONS))],
    ) -> list[OperationResult]:
        with database_factory()() as session:
            rows = OperationRepository(session).list_for_company(record.company_id)
            return [
                OperationResult(
                    request_id=row.request_id,
                    agent_id=row.agent_id,
                    operation=row.operation,
                    amount_cents=row.amount_cents,
                    outcome=DecisionOutcome(row.outcome),
                    reason=DecisionReason(row.reason),
                )
                for row in rows
            ]

    @app.get("/api/v1/approvals", response_model=list[ApprovalView], tags=["Approvals"])
    def list_approvals(
        record: Annotated[UserSession, Depends(require(Capability.VIEW_APPROVALS))],
        approval_status: Annotated[
            str, Query(alias="status", pattern="^(pending|approved|rejected|all)$")
        ] = "pending",
        agent_id: UUID | None = None,
        limit: Annotated[int, Query(ge=1, le=200)] = 100,
    ) -> list[ApprovalView]:
        with database_factory()() as session:
            rows = ApprovalRepository(session).list(
                company_id=record.company_id,
                status=approval_status,
                agent_id=agent_id,
                limit=limit,
            )
            return [approval_view(row) for row in rows]

    @app.get(
        "/api/v1/approvals/{operation_id}",
        response_model=ApprovalView,
        tags=["Approvals"],
    )
    def get_approval(
        operation_id: UUID,
        record: Annotated[UserSession, Depends(require(Capability.VIEW_APPROVALS))],
    ) -> ApprovalView:
        with database_factory()() as session:
            operation = ApprovalRepository(session).get(
                company_id=record.company_id, operation_id=operation_id
            )
            if operation is None:
                raise HTTPException(
                    status_code=404,
                    detail={"code": "not_found", "message": "approval not found"},
                )
            return approval_view(operation)

    @app.post(
        "/api/v1/approvals/{operation_id}/decision",
        response_model=ApprovalDecisionView,
        tags=["Approvals"],
    )
    def decide_approval(
        operation_id: UUID,
        payload: ApprovalDecisionRequest,
        record: Annotated[UserSession, Depends(require(Capability.DECIDE_APPROVALS))],
    ) -> ApprovalDecisionView:
        with database_factory()() as session:
            try:
                decision = ApprovalService(session).decide(
                    company_id=record.company_id,
                    operation_id=operation_id,
                    user_id=record.user_id,
                    decision=payload.decision,
                    reason=payload.reason,
                )
            except ApprovalNotFoundError as error:
                raise HTTPException(
                    status_code=404,
                    detail={"code": "not_found", "message": "approval not found"},
                ) from error
            except OperationNotApprovableError as error:
                raise HTTPException(
                    status_code=409,
                    detail={
                        "code": "operation_not_approvable",
                        "message": "operation did not require human approval",
                    },
                ) from error
            except ApprovalConflictError as error:
                raise HTTPException(
                    status_code=409,
                    detail={
                        "code": "approval_already_decided",
                        "message": "operation already has a human decision",
                    },
                ) from error
            return ApprovalDecisionView(
                id=decision.id,
                decision=decision.decision,
                reason=decision.reason,
                decided_by_user_id=decision.decided_by_user_id,
                created_at=decision.created_at,
            )

    @app.get(
        "/api/v1/audit-events",
        response_model=list[AuditEventView],
        tags=["Audit"],
    )
    def list_audit_events(
        record: Annotated[UserSession, Depends(require(Capability.VIEW_AUDIT))],
        actor_type: AuditActorType | None = None,
        action: str | None = None,
        target_type: str | None = None,
        created_from: datetime | None = None,
        created_to: datetime | None = None,
        limit: Annotated[int, Query(ge=1, le=200)] = 100,
    ) -> list[AuditEventView]:
        with database_factory()() as session:
            events = AuditRepository(session).list_for_company(
                company_id=record.company_id,
                actor_type=actor_type,
                action=action,
                target_type=target_type,
                created_from=created_from,
                created_to=created_to,
                limit=limit,
            )
            return [audit_view(event) for event in events]

    return app


app = create_app()
